"""Initial Migration

Revision ID: 56eda73de74d
Revises: 4b4b09fbf420
Create Date: 2021-04-29 08:39:57.008266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eda73de74d'
down_revision = '4b4b09fbf420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('title', sa.String(length=255), nullable=False))
    op.drop_index('ix_pitches_name', table_name='pitches')
    op.drop_column('pitches', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_pitches_name', 'pitches', ['name'], unique=False)
    op.drop_column('pitches', 'title')
    # ### end Alembic commands ###
