"""Initial Migration

Revision ID: 5f0f823e4d70
Revises: 2d184e748416
Create Date: 2021-04-28 14:20:50.958067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0f823e4d70'
down_revision = '2d184e748416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('post', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'post')
    # ### end Alembic commands ###
